# Generated by Django 4.1 on 2022-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="AIFA1.jpg", upload_to=""),
        ),
    ]
